INSERT INTO discount_policy (DISCOUNT_VALUE, MIN_NUMBER_ORDERED, DISCOUNT_TYPE, PRODUCT_ID)
VALUES (10.0, 5, 'PERCENTAGE', '123');

INSERT INTO discount_policy (DISCOUNT_VALUE, MIN_NUMBER_ORDERED, DISCOUNT_TYPE, PRODUCT_ID)
VALUES (2.5, 10, 'COUNT', '123');

INSERT INTO discount_policy (DISCOUNT_VALUE, MIN_NUMBER_ORDERED, DISCOUNT_TYPE, PRODUCT_ID)
VALUES (15.0, 3, 'PERCENTAGE', '123');

INSERT INTO discount_policy (DISCOUNT_VALUE, MIN_NUMBER_ORDERED, DISCOUNT_TYPE, PRODUCT_ID)
VALUES (1.0, 1, 'COUNT', '123');

INSERT INTO discount_policy (DISCOUNT_VALUE, MIN_NUMBER_ORDERED, DISCOUNT_TYPE, PRODUCT_ID)
VALUES (20.0, 8, 'PERCENTAGE', '1235');